version: "3.8"

volumes:
  data:
    name: external_vol-portainer-data
    external: true

networks:
  portainer:
    name: external_net-portainer
    external: true

services:
  portainer:
    image: portainer/portainer-ce:2.19.4
    # command: -H tcp://tasks.agent:9001 --tlsskipverify
    env_file: external_env-portainer.env
    volumes:
      - data:/data
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
      - target: 9443
        published: 9443
        protocol: tcp
        mode: ingress
    networks:
      - portainer
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          # - node.role == manager
          - node.labels.portainer-ce == anyone
        preferences:
          - spread: node.platform.os
      labels:
        "com.github.xiaoyao9184.docker-seed.type": "stack-standalone"
        "com.github.xiaoyao9184.docker-seed.creator": "seed-container-workspace"
      # resources:
      #   limits:
      #     cpus: '4'
      #     memory: 4096M
      #   reservations:
      #     cpus: '2'
      #     memory: 2048M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 60s
      rollback_config:
        parallelism: 0
        delay: 0s
        failure_action: pause
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
      update_config:
        parallelism: 0
        delay: 0s
        failure_action: rollback
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
