#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ env_path | default('') }}"
  hosts: "{{ 'docker:&docker-lgtm-grafana' if (groups['docker-lgtm-grafana'] is defined) else 'docker' }}"
  tasks:

    - name: fact workspace
      include_tasks: "{{ workspace.local }}/.seed/ansible-tasks/seed-workspace.fact.yml"

    - name: fact workpath
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"
      vars:
        workpath:
          index: -2

    - name: deploy stack
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-stack.deploy.yml"
      vars:
        stack:
          volumes:
            - name: external_vol-grafana-lib
              driver: local
            - name: external_vol-grafana-provisioning
              driver: local
          networks:
            - group: docker-manager
              name: external_net-lgtm
              driver: overlay
              attachable: true
          labels:
            - group: docker-manager
              labels:
                lgtm-grafana: 'anyone'
          envs:
            - file: external_env-grafana.env
              content: |
                GF_LOG_MODE=console
          composes:
            - file: docker-compose-swarm.yml
              src: "{{ playbook_dir }}/docker-compose-swarm.yml"
          share:
            once: true
          override: "{{ lgtm.grafana | default({},true) }}"
