version: "3.8"

volumes:
  lib:
    name: external_vol-grafana-lib
    external: true
  provisioning:
    name: external_vol-grafana-provisioning
    external: true

networks:
  lgtm:
    name: external_net-lgtm
    external: true

services:
  grafana:
    image: grafana/grafana:10.2.3
    env_file: external_env-grafana.env
    volumes:
      - lib:/var/lib/grafana
      - provisioning:/etc/grafana/provisioning
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    networks:
      - lgtm
    # healthcheck:
    #   test: curl -f http://localhost:3000 || exit 1
    #   interval: 60s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 10m
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.lgtm-grafana == anyone
        preferences:
          - spread: node.platform.os
      labels:
        "com.github.xiaoyao9184.docker-seed.type": "stack-standalone"
        "com.github.xiaoyao9184.docker-seed.creator": "seed-container-workspace"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 60s
      rollback_config:
        parallelism: 0
        delay: 0s
        failure_action: pause
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
      update_config:
        parallelism: 0
        delay: 0s
        failure_action: rollback
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
