target: all

multitenancy_enabled: true

stream_over_http_enabled: true

server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
        grpc:
        thrift_binary:
        thrift_compact:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
    opencensus:

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

compactor:
  compaction:
    block_retention: 1h                # overall Tempo trace retention. set for demo purposes

ingester:
  max_block_duration: 5m               # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: anyone-grafanalabs-lgtm
  storage:
    path: /storage/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /storage/tempo/wal             # where to store the the wal locally
    local:
      path: /storage/tempo/blocks

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks] # enables metrics generator

memberlist:
  join_members:
    - tempo:7946

usage_report:
  reporting_enabled: false
