version: "3.8"

networks:
  cadvisor:
    name: external_net-cadvisor
    external: true

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    hostname: "{{.Node.ID}}"
    env_file: external_env-cadvisor.env
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - target: 8080
        published: 9081
        protocol: tcp
        mode: host
    networks:
      - cadvisor
    deploy:
      endpoint_mode: vip
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.cadvisor-node == global
        preferences:
          - spread: node.platform.os
      labels:
        "com.github.xiaoyao9184.docker-seed.type": "stack-scale"
        "com.github.xiaoyao9184.docker-seed.creator": "seed-container-workspace"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 60s
      rollback_config:
        parallelism: 0
        delay: 0s
        failure_action: pause
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
      update_config:
        parallelism: 0
        delay: 0s
        failure_action: rollback
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
