#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ env_path | default('') }}"
  hosts: "{{ 'docker:&docker-cncf-registry' if (groups['docker-cncf-registry'] is defined) else 'docker' }}"
  tasks:

    - name: fact workspace
      include_tasks: "{{ workspace.local }}/.seed/ansible-tasks/seed-workspace.fact.yml"

    - name: fact workpath
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

    - name: deploy stack
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-stack.deploy.yml"
      vars:
        stack:
          volumes:
            - name: external_vol-registry-lib
              driver: local
            - name: external_vol-registry-certs
              driver: local
            - name: external_vol-registry-auth
              driver: local
          networks:
            - group: docker-manager
              name: external_net-registry
              driver: overlay
              attachable: true
          labels:
            - group: docker-manager
              labels:
                registry: 'anyone'
          envs:
            - file: external_env-registry.env
              content: |
                # REGISTRY_HTTP_ADDR=0.0.0.0:5000
                # REGISTRY_HTTP_ADDR=0.0.0.0:443 \
                # REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
                # REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
                # REGISTRY_AUTH=htpasswd
                # REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
                # REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
          composes:
            - file: docker-compose-swarm.yml
              src: "{{ playbook_dir }}/docker-compose-swarm.yml"
          share:
            once: true
          override: "{{ registry | default({},true) }}"
