version: "3.8"

volumes:
  data:
    name: external_vol-alertmanager-data
    external: true

networks:
  prom:
    name: external_net-prom
    external: true

configs:
  alertmanager.yml:
    name: stack_cfg-alertmanager.yml
    file: ../config/alertmanager.yml

services:
  alertmanager:
    image: prom/alertmanager:v0.26.0
    env_file: external_env-alertmanager.env
    # command: --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug
    configs:
      - source: alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
    volumes:
      - data:/alertmanager
    # ports:
    #   - target: 9093
    #     published: 9093
    #     protocol: tcp
    #     mode: ingress
    networks:
      - prom
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.prom-alertmanager == anyone
        preferences:
          - spread: node.platform.os
      labels:
        "com.github.xiaoyao9184.docker-seed.type": "stack-standalone"
        "com.github.xiaoyao9184.docker-seed.creator": "seed-container-workspace"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 60s
      rollback_config:
        parallelism: 0
        delay: 0s
        failure_action: pause
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
      update_config:
        parallelism: 0
        delay: 0s
        failure_action: rollback
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
