#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ env_path | default('') }}"
  hosts: "{{ 'docker:&docker-nfs-node' if (groups['docker-nfs-node'] is defined) else 'docker' }}"
  tasks:

    - name: fact workspace
      include_tasks: "{{ workspace.local }}/.seed/ansible-tasks/seed-workspace.fact.yml"

    - name: fact workpath
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

    - name: deploy compose
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-compose.deploy.yml"
      vars:
        compose:
          files:
            - path: "{{ workpath.remote.full }}/data"
              copy: "{{ playbook_dir }}/data/"
            - path: "{{ workpath.remote.full }}/bind_file-exports"
              redirect: "{{ playbook_dir }}/exports/exports"
          volumes:
            - name: external_vol-nfs-server-data
              driver: local
              push:
                - remote_src: true
                  src: "{{ workpath.remote.full }}/data/"
                  dest: ""
                  directory_mode: '0777'
          envs:
            - file: external_env-all.env
              content: |
                NFS_DISABLE_VERSION_3=true
          composes:
            - file: docker-compose.yml
              template: "{{ playbook_dir }}/docker-compose.yml.j2"
              vars:
                PORTS:
                  - 2049:2049
                  - 2049:2049/udp
          override: "{{ nfs_server | default({},true) }}"
