version: "3.8"

volumes:
  elasticsearch-config:
    name: external_vol-elasticsearch-config
    external: true
  elasticsearch-data:
    name: external_vol-elasticsearch-data
    external: true

networks:
  elk:
    name: external_net-elk
    external: true
  elasticsearch:
    name: external_net-elasticsearch
    external: true

configs:
  elasticsearch.yml:
    name: external_cfg-elasticsearch.yml
    file: ../config/elasticsearch.yml

services:
  elasticsearch:
    image: elastic/elasticsearch:7.17.9
    env_file: external_env-elasticsearch.env
    configs:
      - source: elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - elasticsearch-config:/usr/share/elasticsearch/config
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: ingress
    networks:
      - elk
      - elasticsearch
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.elk-elasticsearch == anyone
        preferences:
          - spread: node.platform.os
      labels:
        "com.github.xiaoyao9184.docker-seed.type": "stack-standalone"
        "com.github.xiaoyao9184.docker-seed.creator": "seed-container-workspace"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 60s
      rollback_config:
        parallelism: 0
        delay: 0s
        failure_action: pause
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
      update_config:
        parallelism: 0
        delay: 0s
        failure_action: rollback
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
