
scrape_configs:
  # - job_name: blackbox
  #   metrics_path: /probe
  #   params:
  #     module:
  #       - http_2xx
  #     target:
  #       - prometheus.io
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['blackbox-exporter:9115']

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://hub.docker.com
        - https://ghcr.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
