#!/usr/bin/env -S ansible-playbook -K -i ${PWD}/ansible-inventories
# code: language=ansible
---

# https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-debian-10
- name: config
  hosts: linux
  become: true
  tasks:

    - rescue:
      - name: rescue|fail tasks
        when:
          - hostvars[inventory_hostname].timesyncd | default(None,true) != None
        ansible.builtin.fail:
          msg: "config fail. exclude host var assert."

      block:
      - name: assert host var
        ansible.builtin.assert:
          that:
            - hostvars[inventory_hostname].timesyncd | default(None,true) != None
          msg: "host var assert fail 'timesyncd'"
          quiet: true

      # not work with chrony
      - name: masked ntp/chrony service
        become: true
        loop:
          - ntp
          - chrony
        ansible.builtin.systemd_service:
          state: stopped
          masked: true
          name: "{{ item }}"
        ignore_errors: true

      - name: install timesyncd package
        become: true
        ansible.builtin.package:
          name: systemd-timesyncd
          state: present
        register: timesyncd_package_install
        until: timesyncd_package_install is succeeded

      - name: unmasked timesyncd service
        become: true
        ansible.builtin.systemd_service:
          state: stopped
          masked: false
          name: systemd-timesyncd
        ignore_errors: true

      - name: start timesyncd service
        become: true
        ansible.builtin.service:
          state: started
          enabled: true
          name: systemd-timesyncd

      - vars:
          mode: "{{ timesyncd.conf.mode | default('none',true) }}"
        block:
        - name: lineinfile replace timesyncd conf
          loop: "{{ timesyncd.conf.lineinfile | default([]) | list }}"
          vars:
            _default:
              path: /etc/systemd/timesyncd.conf
              backup: true
              create: true
            _lineinfile: "{{ item | combine(_default, recursive=True) }}"
          when:
            - mode == 'lineinfile'
          ansible.builtin.lineinfile: "{{ _lineinfile }}"

        - name: copy replace timesyncd conf
          loop: "{{ timesyncd.conf.cp | default([]) | list }}"
          vars:
            _default:
              dest: /etc/systemd/timesyncd.conf
              backup: true
            _copy: "{{ item | combine(_default, recursive=True) }}"
          when:
            - mode == 'cp'
          ansible.builtin.copy: "{{ _copy }}"

        - name: restart timesyncd service
          ansible.builtin.service:
            state: restarted
            enabled: true
            name: systemd-timesyncd

      # About the only way to set the time with timesyncd is manually
      # https://serverfault.com/questions/948974/force-systemd-timesyncd-to-sync-time-with-ntp-server-immediately
      # - name: sync time
      #   ansible.builtin.shell: timedatectl set-time "2019-06-22 13:41:00"

      - name: config ntp synchronization
        ansible.builtin.shell:
          cmd: timedatectl set-ntp true

      - block:
        - name: shell timesyncd status
          loop:
            - timedatectl timesync-status
            - timedatectl
          ansible.builtin.shell:
            cmd: "{{ item }}"
          register: timesyncd_status_shell
          ignore_errors: true

        - name: print status output
          vars:
            linux_hostvars: "{{ hostvars | dict2items
              | selectattr('key','in',ansible_play_hosts)
              | selectattr('value.timesyncd_status_shell','defined') }}"
          ansible.builtin.pause:
            seconds: 1
            prompt: |
              {% for host in linux_hostvars %}

              [{{ host.key }}] =>
              {%   for item in host.value.timesyncd_status_shell.results %}
              --------------------------------------------------
              $ {{ item.item }}
              {{ item.stdout | default('',true) }}
              {{ item.stderr | default('',true) }}
              {%   endfor %}
              {% endfor %}
