# code: language=ansible

files:
  - group: docker-manager
    src: "{{ playbook_dir }}/../config/prometheus.yml"
    dest: "{{ workpath.remote.full }}/../config/prometheus.yml"
  - src: "{{ playbook_dir }}/scrape/scrapes/"
    dest: "{{ workpath.remote.full }}/scrape/scrapes/"
  - src: "{{ playbook_dir }}/rule/rules/"
    dest: "{{ workpath.remote.full }}/rule/rules/"
volumes:
  - name: external_vol-prometheus-data
    driver: local
  - name: external_vol-prometheus-etc
    driver: local
    push:
      - dest: "scrapes"
        directory_mode: '0777'
      - remote_src: true
        src: "{{ workpath.remote.full }}/scrape/scrapes/"
        dest: "scrapes"
        directory_mode: '0777'
      - dest: "rules"
        directory_mode: '0777'
      - remote_src: true
        src: "{{ workpath.remote.full }}/rule/rules/"
        dest: "rules"
        directory_mode: '0777'
networks:
  - group: docker-manager
    name: external_net-prom
    driver: overlay
    attachable: true
  - group: docker-manager
    name: external_net-mimir
    driver: overlay
    attachable: true
labels:
  - group: docker-manager
    labels:
      prom-prometheus: 'true'
envs:
  - file: external_env-prometheus.env
    content: ''
composes:
  - file: docker-compose-swarm.yml
    src: "{{ playbook_dir }}/docker-compose-swarm.yml"
share:
  once: true
override: "{{ prom.prometheus | default({},true) }}"
