#!/usr/bin/env -S ansible-playbook -K -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: config
  hosts: linux
  tasks:

    - name: config for localhost
      become: true
      vars:
        enable: |
          127.0.0.1 localhost

          # The following lines are desirable for IPv6 capable hosts
          ::1 ip6-localhost ip6-loopback
          fe00::0 ip6-localnet
          ff00::0 ip6-mcastprefix
          ff02::1 ip6-allnodes
          ff02::2 ip6-allrouters
          ff02::3 ip6-allhosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        backup: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK localhost"
        block: "{{ (hosts.localhost | default(true)) | ternary(enable,'') }}"

    - name: config by address hostname
      become: true
      when: (hosts.address | default(false) | type_debug == 'list') | ternary(true,false)
      ansible.builtin.blockinfile:
        path: /etc/hosts
        backup: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK address"
        block: |
          {% for item in ansible_play_hosts %}
          {%   if hostvars[item].hostname is defined %}
          {%     for key in hosts.address %}
          {%       if hostvars[item][key].address is defined %}
          {{ hostvars[item][key].address }} {{ hostvars[item].hostname }}
          {%       endif %}
          {%     endfor %}
          {%   endif %}
          {% endfor %}

    - name: config by content variable
      become: true
      when: hosts.content is defined
      ansible.builtin.blockinfile:
        path: /etc/hosts
        backup: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK content"
        block: "{{ hosts.content }}"
