#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ env_path | default('') }}"
  hosts: "{{ 'docker:&docker-tick-node' if (groups['docker-tick-node'] is defined) else 'docker' }}"
  tasks:

    - name: fact workspace
      include_tasks: "{{ workspace.local }}/.seed/ansible-tasks/seed-workspace.fact.yml"

    - name: fact workpath
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

    - name: deploy stack
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-stack.deploy.yml"
      vars:
        stack:
          files:
            - group: docker-manager
              path: "{{ workpath.remote.full }}/config/telegraf.conf"
              copy: "{{ playbook_dir }}/config/telegraf.conf"
            - group: docker-manager
              path: "{{ workpath.remote.full }}/config/influxdb.conf"
              copy: "{{ playbook_dir }}/config/influxdb.conf"
            - group: docker-manager
              path: "{{ workpath.remote.full }}/config/kapacitor.conf"
              copy: "{{ playbook_dir }}/config/kapacitor.conf"
          networks:
            - group: docker-manager
              name: external_net-tick
              driver: overlay
              attachable: true
            - group: docker-manager
              name: external_net-telegraf
              driver: overlay
              attachable: true
            - group: docker-manager
              name: external_net-influxdb
              driver: overlay
              attachable: true
            - group: docker-manager
              name: external_net-kapacitor
              driver: overlay
              attachable: true
          labels:
            - group: docker-manager
              labels:
                tick-node: 'true'
                tick-telegraf: 'mix'
                tick-influxdb: 'mix'
                tick-chronograf: 'mix'
                tick-kapacitor: 'mix'
          envs:
            - file: external_env-telegraf.env
              content: ''
            - file: external_env-influxdb.env
              content: ''
            - file: external_env-chronograf.env
              content: ''
            - file: external_env-kapacitor.env
              content: ''
          composes:
            - file: docker-compose-swarm.yml
              src: "{{ playbook_dir }}/docker-compose-swarm.yml"
          share:
            once: true
          override: "{{ tick | default({},true) }}"
