version: "3.8"

volumes:
  influxdb-lib:
    name: external_vol-influxdb-lib
    external: true
  influxdb-config:
    name: external_vol-influxdb-config
    external: true

networks:
  tick:
    name: external_net-tick
    external: true
  influxdb:
    name: external_net-influxdb
    external: true

configs:
  influxdb.conf:
    name: stack_cfg-influxdb.conf
    file: ../config/influxdb.conf

services:
  influxdb:
    image: influxdb:1.8.10
    env_file: external_env-influxdb.env
    configs:
      - source: influxdb.conf
        target: /etc/influxdb/influxdb.conf
    volumes:
      - influxdb-lib:/var/lib/influxdb
      - influxdb-config:/etc/influxdb
    ports:
      - target: 8086
        published: 8086
        protocol: tcp
        mode: ingress
      # - 2003:2003
      # - 25826:25826
      # - 4242:4242
      # - 8088:8088
      # - 8089:8089
    networks:
      - tick
      - influxdb
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.tick-influxdb == anyone
        preferences:
          - spread: node.platform.os
      labels:
        "com.github.xiaoyao9184.docker-seed.type": "stack-standalone"
        "com.github.xiaoyao9184.docker-seed.creator": "seed-container-workspace"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 60s
      rollback_config:
        parallelism: 0
        delay: 0s
        failure_action: pause
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
      update_config:
        parallelism: 0
        delay: 0s
        failure_action: rollback
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
