version: "3.8"

volumes:
  schema-registry-secrets:
    name: external_vol-schema-registry-secrets
    external: true

networks:
  cp:
    name: external_net-cp
    external: true
  kafka:
    name: external_net-kafka
    external: true

services:
  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.0
    env_file: external_env-schema-registry.env
    environment:
      # SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    volumes:
      - schema-registry-secrets:/etc/schema-registry/secrets
    ports:
      - "8081:8081"
    networks:
      - cp
      - kafka
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.cp-schema-registry == anyone
        preferences:
          - spread: node.platform.os
      labels:
        "com.github.xiaoyao9184.docker-seed.type": "stack-standalone"
        "com.github.xiaoyao9184.docker-seed.creator": "seed-container-workspace"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 60s
      rollback_config:
        parallelism: 0
        delay: 0s
        failure_action: pause
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
      update_config:
        parallelism: 0
        delay: 0s
        failure_action: rollback
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
