#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ env_path | default('') }}"
  hosts: "{{ 'docker:&docker-prom-prometheus' if (groups['docker-prom-prometheus'] is defined) else 'docker' }}"
  tasks:

    - name: fact workspace
      include_tasks: "{{ workspace.local }}/.seed/ansible-tasks/seed-workspace.fact.yml"

    - name: fact workpath
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"
      vars:
        workpath:
          index: -2

    - name: deploy stack
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-stack.deploy.yml"
      vars:
        stack:
          files:
            - group: docker-manager
              src: "{{ playbook_dir }}/../config/prometheus.yml"
              dest: "{{ workpath.remote.full }}/../config/prometheus.yml"
            - src: "{{ playbook_dir }}/scrape/scrapes/"
              dest: "{{ workpath.remote.full }}/scrape/scrapes/"
            - src: "{{ playbook_dir }}/rule/rules/"
              dest: "{{ workpath.remote.full }}/rule/rules/"
          volumes:
            - name: external_vol-prometheus-data
              driver: local
            - name: external_vol-prometheus-etc
              driver: local
              push:
                - dest: "scrapes"
                  directory_mode: '0777'
                - remote_src: true
                  src: "{{ workpath.remote.full }}/scrape/scrapes/"
                  dest: "scrapes"
                  directory_mode: '0777'
                - dest: "rules"
                  directory_mode: '0777'
                - remote_src: true
                  src: "{{ workpath.remote.full }}/rule/rules/"
                  dest: "rules"
                  directory_mode: '0777'
          networks:
            - group: docker-manager
              name: external_net-prom
              driver: overlay
              attachable: true
          labels:
            - group: docker-manager
              labels:
                prom-prometheus: 'true'
          envs:
            - file: external_env-prometheus.env
              content: ''
          composes:
            - file: docker-compose-swarm.yml
              src: "{{ playbook_dir }}/docker-compose-swarm.yml"
          share:
            once: true
          override: "{{ prom.prometheus | default({},true) }}"
