version: "3.8"

volumes:
  data:
    name: external_vol-prometheus-data
    external: true
  etc:
    name: external_vol-prometheus-etc
    external: true

networks:
  prom:
    name: external_net-prom
    external: true
  prometheus:
    name: external_net-prometheus
    external: true

configs:
  prometheus.yml:
    name: stack_cfg-prometheus.yml
    file: ../config/prometheus.yml

services:
  prometheus:
    image: prom/prometheus:v2.48.0
    env_file: external_env-prometheus.env
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    volumes:
      - data:/prometheus
      - etc:/etc/prometheus
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: ingress
    networks:
      - prom
      - prometheus
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.prom-prometheus == anyone
        preferences:
          - spread: node.platform.os
      labels:
        "com.github.xiaoyao9184.docker-seed.type": "stack-standalone"
        "com.github.xiaoyao9184.docker-seed.creator": "seed-container-workspace"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 60s
      rollback_config:
        parallelism: 0
        delay: 0s
        failure_action: pause
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
      update_config:
        parallelism: 0
        delay: 0s
        failure_action: rollback
        monitor: 5m
        max_failure_ratio: 0
        order: stop-first
