#!/usr/bin/env -S ansible-playbook -K -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: config
  hosts: linux
  tasks:

    - name: change hostname
      become: true
      when: hostname is defined
      ansible.builtin.hostname:
        name: "{{ hostname }}"
